field.formatter.settings.epa_core_hierarchical_term_facet_formatter:
  type: mapping
  label: 'EPA Core Hierarchical Term Facet Formatter settings'
  mapping:
    display:
      type: string
      label: 'Whether to display all elements or a specified amount'
    link:
      type: boolean
      label: 'Whether the terms should link to the entity'
    wrap:
      type: string
      label: 'The HTML structure to wrap elements'
    separator:
      type: string
      label: 'The string that should separate each term'
    reverse:
      type: boolean
      label: 'Whether display order should be in descendant fashion'
    facet_srouce:
      type: string
      label: 'The Facet Source ID'

