# Design Tokens
# Define basic design variables here.
uswds:
  image-path: '../images'
  root-font-size: 16px
  font-weight-semibold: 600
  show-compile-warnings: false
  grid-container-max-width: 'widescreen'
  column-gap-desktop: 5
gesso:
  palette:
    brand:
      blue:
        base: !sass
          sass: 'color("blue-60v")'
          fallback: '#005ea2'
        light: !sass
          sass: 'color("blue-40")'
          fallback: '#4f97d1'
        light-1: !sass
          sass: 'color("blue-20")'
          fallback: '#aacdec'
        light-2: !sass
          sass: 'sass("blue-10")'
          fallback: '#d9e8f6'
        dark: !sass
          sass: 'sass("blue-warm-70v")'
          fallback: '#1a4480'
        dark-1: !sass
          sass: 'sass("blue-warm-80v")'
          fallback: '#162e51'
      ocean-blue:
        base: !sass
          sass: 'color("cyan-30v")'
          fallback: '#00bde3'
        light: !sass
          sass: 'color("blue-cool-20v")'
          fallback: '#97d4ea'
        light-1: !sass
          sass: 'color("blue-cool-5v")'
          fallback: '#e1f3f8'
        dark: !sass
          sass: 'color("blue-cool-40v")'
          fallback: '#28a0cb'
        dark-1: !sass
          sass: 'color("blue-cool-60v")'
          fallback: '#07648d'
    grayscale:
      white: '#fff'
      gray-1: !sass
        sass: 'color("gray-cool-5")'
        fallback: '#f0f0f0'
      gray-2: !sass
        sass: 'color("gray-cool-10")'
        fallback: '#dcdee0'
      gray-3: !sass
        sass: 'color("gray-cool-30")'
        fallback: '#a9aeb1'
      gray-4: !sass
        sass: 'color("gray-cool-50")'
        fallback: '#71767a'
      gray-5: !sass
        sass: 'color("gray-cool-60")'
        fallback: '#565c65'
      gray-6: !sass
        sass: 'color("gray-cool-70")'
        fallback: '#3d4551'
      black: !sass
        sass: 'color("gray-90")'
        fallback: '#1b1b1b'
    other:
      yellow:
        base: !sass
          sass: 'color("yellow-20v")'
          fallback: '#face00'
        light: !sass
          sass: 'color("yellow-10v")'
          fallback: '#fee685'
      yellow-neon:
        base: '#ff0'
      green:
        base: !sass
          sass: 'color("green-40")'
          fallback: '#7d9b4e'
        light: !sass
          sass: 'color("green-10")'
          fallback: '#dfeacd'
      red:
        base: !sass
          sass: 'color("red-50")'
          fallback: '#d83933'
        light: !sass
          sass: 'color("red-30")'
          fallback: '#f2938c'
        light-1: !sass
          sass: 'color("red-cool-10v")'
          fallback: '#f8dfe2'
        dark: !sass
          sass: 'color("red-60v")'
          fallback: '#b51d09'
        dark-1: !sass
          sass: 'color("red-70v")'
          fallback: '#8b1303'
  box-shadow:
    0: none
    1: !sass
      sass: 'shadow(1)'
      fallback: '0 1px 4px 0 rgba(0, 0, 0, 0.1)'
    2: !sass
      sass: 'shadow(2)'
      fallback: '0 4px 8px 0 rgba(0, 0, 0, 0.1)'
    3: !sass
      sass: 'shadow(3)'
      fallback: '0 8px 16px 0 rgba(0, 0, 0, 0.1)'
    4: !sass
      sass: 'shadow(4)'
      fallback: '0 12px 24px 0 rgba(0, 0, 0, 0.1)'
    5: !sass
      sass: 'shadow(5)'
      fallback: '0 16px 32px 0 rgba(0, 0, 0, 0.1)'
  constrains:
    sm: 800px
    md: !uswds uswds.grid-container-max-width
    lg: 2200px
  breakpoints:
    xs: !sass
      sass: 'units("mobile-lg")'
      fallback: 480px
    sm: !sass
      sass: 'units("tablet")'
      fallback: 640px
    md: !sass
      sass: 'units("desktop")'
      fallback: 1024px
    lg: !sass
      sass: 'units("widescreen")'
      fallback: 1400px
  colors:
    text:
      primary: grayscale.black
      secondary: grayscale.gray-5
      on-light: grayscale.black
      on-dark: grayscale.white
      link: brand.blue.base
      link-hover: brand.blue.dark
      link-active: brand.blue.dark
      link-visited: brand.blue.dark
    background:
      site: grayscale.white
    button:
      primary:
        background: brand.blue.base
        background-hover: brand.blue.dark
        background-active: brand.blue.dark-1
        text: grayscale.white
        text-hover: grayscale.white
        text-active: grayscale.white
      secondary:
        background: brand.ocean-blue.base
        background-hover: brand.ocean-blue.dark
        background-active: brand.ocean-blue.dark-1
        text: grayscale.white
        text-hover: grayscale.white
        text-active: grayscale.white
      disabled:
        background: grayscale.gray-2
        text: grayscale.gray-4
      danger:
        background: other.red.base
        background-hover: other.red.dark
        background-active: other.red.dark-1
        text: grayscale.white
        text-hover: grayscale.white
        text-active: grayscale.white
    form:
      background: grayscale.gray-1
      background-active: grayscale.white
      background-checked: brand.blue.base
      background-unchecked: grayscale.white
      border: grayscale.gray-3
      border-dark: grayscale.gray-5
      border-light: grayscale.gray-1
      thumb: grayscale.gray-5
      track: grayscale.gray-4
    mark:
      background: other.yellow-neon.base
      text: grayscale.black
    selection:
      background: brand.blue.base
      text: grayscale.white
    table:
      border: grayscale.gray-5
      background: grayscale.white
      background-head: grayscale.gray-2
      background-foot: grayscale.gray-2
    ui:
      generic:
        background: grayscale.gray-4
        background-darker: grayscale.black
        background-dark: grayscale.gray-6
        background-light: grayscale.gray-2
        background-lighter: grayscale.gray-1
        border: grayscale.gray-4
        border-dark: grayscale.gray-6
        border-light: grayscale.gray-2
        text-lighter: grayscale.white
        text-light: grayscale.gray-4
        text-dark: grayscale.gray-5
        text-darker: grayscale.black
        accent: brand.blue.base
        accent-dark: brand.blue.dark-1
        accent-light: brand.blue.light
        focus: brand.blue.light
      error:
        background: other.red.light-1
        border: other.red.light
      success:
        background: other.green.light
        border: other.green.base
      warning:
        background: other.yellow.light
        border: other.yellow.base
  typography:
    font-family:
      primary:
        name: Primary
        stack: !sass
          sass: 'family("body")'
          fallback: '"Source Sans Pro", "Helvetica Neue", "Helvetica", "Roboto", "Arial", sans-serif'
      system:
        name: System
        stack: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Oxygen-Sans", Ubuntu, Cantarell, "Fira Sans", Droid Sans, sans-serif'
      monospace:
        name: Monospace
        stack: !sass
          sass: 'family("mono")'
          fallback: '"Roboto Mono Web", "Roboto Mono Web", "Bitstream Vera Sans Mono", "Consolas", "Courier", monospace'
    base-font-size: uswds.root-font-size
    font-size:
      0: !sass
        sass: 'size("body", "3xs")'
        fallback: 13px
      1: !sass
        sass: 'size("body", "2xs")'
        fallback: 14px
      2: !sass
        sass: 'size("body", "xs")'
        fallback: 15px
      3: !sass
        sass: 'size("body", "sm")'
        fallback: 16px
      4: !sass
        sass: 'size("heading", "md")'
        fallback: 17px
      5: !sass
        sass: 'size("heading", "lg")'
        fallback: 22px
      6: !sass
        sass: 'size("heading", "xl")'
        fallback: 32px
      7: !sass
        sass: 'size("heading", "2xl")'
        fallback: 40px
      8: !sass
        sass: 'size("heading", "3xl")'
        fallback: 48px
      9: !sass
        sass: 'size("heading", 18)'
        fallback: 80px
    font-weight:
      light: !sass
        sass: 'font-weight("light")'
        fallback: 300
      regular: !sass
        sass: 'font-weight("normal")'
        fallback: 400
      semibold: !sass
        sass: 'font-weight("semibold")'
        fallback: 600
      bold: !sass
        sass: 'font-weight("bold")'
        fallback: 700
    line-height:
      tight: 1.1
      base: 1.45
      loose: 1.7
    display:
      display:
        color: text.primary
        font-family: primary.stack
        font-size: 8
        font-weight: bold
        line-height: tight
      h1:
        color: text.primary
        font-family: primary.stack
        font-size: 7
        font-weight: bold
        line-height: tight
      h2:
        color: text.primary
        font-family: primary.stack
        font-size: 6
        font-weight: bold
        line-height: tight
      h3:
        color: text.primary
        font-family: primary.stack
        font-size: 5
        font-weight: bold
        line-height: tight
      h4:
        color: text.primary
        font-family: primary.stack
        font-size: 4
        font-weight: bold
        line-height: base
      h5:
        color: text.primary
        font-family: primary.stack
        font-size: 2
        font-weight: bold
        line-height: base
      h6:
        color: text.primary
        font-family: primary.stack
        font-size: 0
        font-weight: semibold
        letter-spacing: -0.04em
        line-height: loose
        text-transform: uppercase
      blockquote:
        color: text.link
        font-family: primary.stack
        font-size: 5
        font-weight: regular
        line-height: base
      body:
        color: text.primary
        font-family: primary.stack
        font-size: 3
        font-weight: regular
        line-height: base
      body-large:
        color: text.primary
        font-family: primary.stack
        font-size: 4
        font-weight: regular
        line-height: base
      cite:
        color: text.secondary
        font-family: primary.stack
        font-size: 0
        font-style: normal
        font-weight: semibold
        letter-spacing: .02em
        line-height: tight
  transitions:
    ease:
      ease-in-out: 'cubic-bezier(0.4, 0, 0.2, 1)'
      ease-out: 'cubic-bezier(0.0, 0, 0.2, 1)'
      ease-in: 'cubic-bezier(0.4, 0, 1, 1)'
      sharp: 'cubic-bezier(0.4, 0, 0.6, 1)'
    duration:
      shortest: 150ms
      short: 200ms
      standard: 375ms
      long: 400ms
      intro: 270ms
      outro: 195ms
  z-index:
    nav: 1000
    drawer: 1200
    modal: 1300
  spacing:
    "05": !sass
      sass: 'units("05")'
      fallback: '4px'
    1: !sass
      sass: 'units(1)'
      fallback: '8px'
    2: !sass
      sass: 'units(2)'
      fallback: '16px'
    3: !sass
      sass: 'units(3)'
      fallback: '24px'
    5: !sass
      sass: 'units(5)'
      fallback: '40px'
    8: !sass
      sass: 'units(8)'
      fallback: '64px'
    15: !sass
      sass: 'units(15)'
      fallback: '120px'
  gutter-width: !uswds uswds.column-gap-desktop
