action.configuration.epa_web_areas_update_node_group_association:
  type: mapping
  label: 'Configuration for "Update Node Group Association" action'
  mapping:
    title:
      type: string
      label: Title
action.configuration.epa_web_areas_update_media_group_association:
  type: mapping
  label: 'Configuration for "Update Media Group Association" action'
  mapping:
    title:
      type: string
      label: Title
