action.configuration.epa_web_areas_update_node_group_association:
  type: mapping
  label: 'Configuration for "Update Node Group Association" action'
  mapping:
    title:
      type: string
      label: Title
action.configuration.epa_web_areas_update_media_group_association:
  type: mapping
  label: 'Configuration for "Update Media Group Association" action'
  mapping:
    title:
      type: string
      label: Title

epa_web_areas.allowed_bulk_change:
  type: mapping
  label: 'Allowed Entity Types'
  mapping:
    entity_type:
      type: string
      label: 'Entity Type'
    bundles:
      type: mapping
      label: 'Bundles'
      mapping:
        bundle:
          type: string
          label: 'Bundle'

