# https://doc.traefik.io/traefik/getting-started/faq/#xxx-instead-of-404
http:
  routers:
    catchall:
      # attached only to web entryPoint
      entryPoints:
        - "websecure"
      # catchall rule
      rule: "PathPrefix(`/`)"
      service: unavailable
      # lowest possible priority
      # evaluated when no other router is matched
      priority: 1

  services:
    # Service that will always answer a 503 Service Unavailable response
    unavailable:
      loadBalancer:
        servers: {}
