extends:
  - stylelint-config-sass-guidelines

plugins:
  - stylelint-order
  - stylelint-prettier
  - stylelint-selector-pseudo-class-lvhfa
rules:
  block-no-empty: null
  color-named:
    - never
    - ignore:
      - 'inside-function'
  max-nesting-depth: 3
  order/properties-alphabetical-order: true
  plugin/selector-pseudo-class-lvhfa: true
  prettier/prettier: true
  property-no-vendor-prefix: null
  selector-class-pattern:
    # "piece" regex:
    # [a-zA-Z0-9]+
    # dash-separated pieces:
    # [a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z][a-zA-Z0-9]*)*
    #
    #   Block                                              Element (optional)                                   Modifier (also optional)
    #   ----------------------------------------------     -----------------------------------------------      -----------------------------------------------
    - '^[a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?$'
  selector-no-qualifying-type:
    - true
    - ignore:
      - attribute
  string-no-newline: true
  scss/at-import-partial-extension-blacklist:
    - 'less'
    - 'sass'
  scss/at-mixin-pattern:
    # "piece" regex:
    # [a-zA-Z0-9]+
    # dash-separated pieces:
    # [a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z][a-zA-Z0-9]*)*
    #
    #   Block                                              Element (optional)                                   Modifier (also optional)
    #   ----------------------------------------------     -----------------------------------------------      -----------------------------------------------
    - '^[a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?$'
  scss/percent-placeholder-pattern:
    # "piece" regex:
    # [a-zA-Z0-9]+
    # dash-separated pieces:
    # [a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z][a-zA-Z0-9]*)*
    #
    #   Block                                              Element (optional)                                   Modifier (also optional)
    #   ----------------------------------------------     -----------------------------------------------      -----------------------------------------------
    - '^[a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?$'
  scss/at-extend-no-missing-placeholder: null
