scheme_whitelist:
  - http
  - https
  - files
  - internal
protocol_style: path
local_paths: "http://es-dev.epa.byf1.io\r\nhttps://es-dev.epa.byf1.io\r\nhttp://es-stage.epa.byf1.io\r\nhttps://es-stage.epa.byf1.io\r\nhttp://es-prod.epa.byf1.io\r\nhttps://es-prod.epa.byf1.io\r\nhttp://es-drupal1.epa.gov\r\nhttps://es-drupal1.epa.gov\r\nhttp://es-drupal2.epa.gov  \r\nhttps://es-drupal2.epa.gov\r\nhttp://es-wcms.epa.gov\r\nhttps://es-wcms.epa.gov\r\nhttp://espanol.epa.gov\r\nhttps://espanol.epa.gov\r\nhttp://es-drupal1-test.epa.gov\r\nhttps://es-drupal1-test.epa.gov\r\nhttp://es-drupal2-test.epa.gov\r\nhttps://es-drupal2-test.epa.gov"
_core:
  default_config_hash: EKYCulG-Y3pcObfUpVbl-D9T5DDX6d4hpQ-BVlSBAmw
